version: "3.9"
services:
  mysql-db:
    container_name: mysql-db
    image: mysql
    environment:
      TZ: America/Bogota
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:-pwd}
      MYSQL_USER: ${MYSQL_USER:-mysql}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD:-pwd}
      MYSQL_DATABASE: ${MYSQL_DATABASE:-transactions}
    restart: unless-stopped
    ports:
      - 3306:3306
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "mysqladmin ping -h 127.0.0.1 -u root --password=${MYSQL_ROOT_PASSWORD:-pwd}",
        ]
      interval: 0.5s
      timeout: 10s
      retries: 10
  storicard-app:
    build:
      context: .
      dockerfile: Dockerfile # Specify the path to your Dockerfile
    environment:
      AWS_REGION: ${AWS_REGION}
      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
      AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
    ports:
      - 3000:3000
    volumes:
      - ./config/config.local.yaml:/app/config/config.local.yaml
    depends_on:
      - mysql-db
    dns:
      - 8.8.8.8
      - 4.4.4.4
